explicit cache warmup

diff --git a/.travis.yml b/.travis.yml
--- a/.travis.yml
+++ b/.travis.yml
@@ -13,7 +13,7 @@ warnings_are_errors: true
 install:
   - if [[ $TRAVIS_OS_NAME == "osx" ]]; then brew install ccache; export PATH="/usr/local/opt/ccache/libexec:$PATH"; fi
   - if [[ $TRAVIS_OS_NAME == "linux" ]]; then export PATH="/usr/lib/ccache:$PATH"; fi
-  - ccache -M 5G
+  - ccache -M 1G
   - ccache -s
 
 branches:
@@ -60,24 +60,43 @@ script:
   - PKG_TARBALL=$(ls -1t *.tar.gz | head -n 1)
   - ls
   - |
-      travis_wait 120 R CMD check ${R_CHECK_ARGS} "${PKG_TARBALL}"
-      RCMDCHECKSTATUS=$?
-      ## Now record the status of the first part of the pipe
-      echo "TRAVIS_WAIT exit status: $RCMDCHECKSTATUS";
-      ## Save the cache
-      ccache -s;
-      travis_run_cache;
-      ## Now check the return values from the check
-
-      if [[ $RCMDCHECKSTATUS -eq 137 ]];
-      then
-         echo "Compilation timed out - try again to see if cache is sufficient"
-      elif [[ $RCMDCHECKSTATUS -eq 0 ]] ;
-      then
-         echo "Check appears to have succeeded"
+      ## Check whether we have a decent sized cache
+      ## so it can be warmed up
+      CSIZE=(du -s ~/.ccache/ | awk '{print $1}')
+      if [ ${CSIZE} -lt 800000 ] ; then
+      	 travis_wait 20 R CMD check ${R_CHECK_ARGS} "${PKG_TARBALL}"
+      	 RCMDCHECKSTATUS=$?
+      	 ## Now record the status of the first part of the pipe
+      	 echo "TRAVIS_WAIT exit status: $RCMDCHECKSTATUS";
+      	 ## Save the cache
+	 travis_run_cache;
+         ## Now check the return values from the check
+         if [[ $RCMDCHECKSTATUS -eq 137 ]];
+         then
+           echo "Compilation timed out - try again to see if cache is sufficient"
+         elif [[ $RCMDCHECKSTATUS -eq 0 ]] ;
+         then
+           echo "Check appears to have succeeded"
+         else
+           echo "Some other failure: $RCMDCHECKSTATUS"
+         fi
       else
-         echo "Some other failure: $RCMDCHECKSTATUS"
-      fi
+         ## attempting a real build
+         travis_wait 160 R CMD check ${R_CHECK_ARGS} "${PKG_TARBALL}"
+      	 RCMDCHECKSTATUS=$?
+      	 ## Now record the status of the first part of the pipe
+      	 echo "TRAVIS_WAIT exit status: $RCMDCHECKSTATUS";
+         ## Now check the return values from the check
+         if [[ $RCMDCHECKSTATUS -eq 137 ]];
+         then
+           echo "Compilation timed out - try again to see if cache is sufficient"
+         elif [[ $RCMDCHECKSTATUS -eq 0 ]] ;
+         then
+           echo "Check appears to have succeeded"
+         else
+           echo "Some other failure: $RCMDCHECKSTATUS"
+         fi
+      fi	 
       #cat travis_wait*.log;
       #rm -f travis_wait*.log;
       #if [[ $FIRSTBUILD -ne 0 ]];
