Fancier processing of the compile step to force ccache to be retained

diff --git a/.travis.yml b/.travis.yml
--- a/.travis.yml
+++ b/.travis.yml
@@ -5,7 +5,6 @@ cache:
   packages: true
   directories:
   - $HOME/.ccache
-  - $HOME/.status
 
 # A status directory for storing which sort of build we have
 warnings_are_errors: true
@@ -60,11 +59,13 @@ script:
   - PKG_TARBALL=$(ls -1t *.tar.gz | head -n 1)
   - ls
   - |
-    if [[ -e $HOME/.status/cachesetup ]];
-    then
-      echo "CCache already there - attempt a real build";
-      travis_wait 170 R CMD check ${R_CHECK_ARGS} "${PKG_TARBALL}"; CHECK_RET=$? ;
+      ## Force the pipe to succeed so that we can save the cache
+      travis_wait 170 R CMD check ${R_CHECK_ARGS} "${PKG_TARBALL}" || true
+      ## Now record the status of the first part of the pipe
+      CHECK_RET=${PIPESTATUS[0]}
+      ## Save the cache
       travis_run_cache;
+      ## Now check the return values from the check
       cat travis_wait*.log;
       rm -f travis_wait*.log;
       if [[ $CHECK_RET -ne 0 ]];
@@ -73,14 +74,6 @@ script:
         check_fail; 
         dump_logs; 
       fi
-     else
-       echo "Setting up ccache for a faster build next time";
-       travis_wait 170 R CMD check ${R_CHECK_ARGS} "${PKG_TARBALL}" || true;
-       mkdir -p $HOME/.status;
-       touch $HOME/.status/cachesetup;
-       travis_run_cache;
-       travis_terminate 1;
-     fi  
   - check_warnings
 
 after_success:
