bump

diff --git a/.circleci/config.yml b/.circleci/config.yml
--- a/.circleci/config.yml
+++ b/.circleci/config.yml
@@ -85,12 +85,88 @@ jobs:
           command: |
             set -x
             R -e "remotes::install_git(c('.'), lib=c('${R_LIBS}'), configure.vars=c('MAKEJ=3'))"
-
+  r-release:
+    parameters:
+      os:
+        type: executor
+      r-version:
+        type: string
+    executor: << parameters.os >>
+    environment:
+      ITK_GLOBAL_DEFAULT_NUMBER_OF_THREADS: 2
+    steps:
+      - checkout
+      - run:
+          name: Set environment
+          command: |
+            echo "export R_LIBS=$HOME/Rlibs" >> $BASH_ENV
+      - run:
+          name: Install R << parameters.r-version >>
+          command: |
+            R_VERSION="<< parameters.r-version >>"
+            # Install rig, R Installation Manager (https://github.com/r-lib/rig) to control installed R version
+            if [ "$RUNNER_OS" == "macos" ]; then
+              brew tap r-lib/rig
+              brew install --cask rig
+              rig add $R_VERSION
+              # on macOS the R package is installed into a MAJOR.MINOR directory
+              # the PATCH is ignored (only one patch version supported) the
+              # architecture is added as a suffix (arm64, x86_64) to allow for
+              # installations to coexist
+              rig default "${R_VERSION%.*}-arm64"
+            elif [ "$RUNNER_OS" == "linux" ]; then
+              `which sudo` curl -L https://rig.r-pkg.org/deb/rig.gpg -o /etc/apt/trusted.gpg.d/rig.gpg
+              `which sudo` sh -c 'echo "deb http://rig.r-pkg.org/deb rig main" > /etc/apt/sources.list.d/rig.list'
+              `which sudo` apt update
+              `which sudo` apt install r-rig
+              sudo rig add $R_VERSION
+              sudo rig default $R_VERSION
+            fi
+      - run:
+          name: System Dependencies
+          command: |
+            if [ "$RUNNER_OS" == "linux" ]; then
+              sudo apt-get -y update
+              sudo apt-get install -y cmake libcurl4-openssl-dev libssh2-1-dev libharfbuzz-dev libfribidi-dev gh
+              sudo rm -rf /var/lib/apt/lists/*
+            elif [ "$RUNNER_OS" == "macos" ]; then
+              brew install cmake
+            fi
+      - run:
+          name: Configuration Information
+          command: |
+            mkdir -p ${R_LIBS}
+            c++ --version
+            cmake --version || echo "cmake not found"
+            which R
+            R --version
+      - run:
+          name: Install R packages
+          command: |
+            R -e "install.packages(c('remotes'), lib=c('${R_LIBS}'), repo='https://cloud.r-project.org/')"
+      - run:
+          name: Build and test
+          no_output_timeout: 30m
+          command: |
+            set -x
+            R -e "remotes::install_git(c('.'), lib=c('${R_LIBS}'), configure.vars=c('MAKEJ=3'))"
 workflows:
   r-build-test:
     # Runs on: push to main, pull requests to main, manual trigger, and scheduled runs
     jobs:
       - r-build:
+          matrix:
+            parameters:
+              r-version: ['4.3.1', '4.4.1']
+              os: ["macos-arm"]
+          filters:
+            branches:
+              only:
+                - release
+  r-release-test:
+    # Runs on: push to main, pull requests to main, manual trigger, and scheduled runs
+    jobs:
+      - r-release:
           matrix:
             parameters:
               r-version: ['4.3.1', '4.4.1']
