initiate release workflows

diff --git a/.circleci/config.yml b/.circleci/config.yml
--- a/.circleci/config.yml
+++ b/.circleci/config.yml
@@ -6,12 +6,18 @@ parameters:
     default: false
 
 executors:
-  windows:
+  linux:
     machine:
-      image: windows-server-2022-gui:current
+      image: ubuntu-2204:current
     environment:
-      RUNNER_OS: windows
-    resource_class: windows.large
+      RUNNER_OS: linux
+    resource_class: large
+  macos-arm:
+    macos:
+      xcode: 16.4.0
+    environment:
+      RUNNER_OS: macos
+    resource_class: m4pro.medium
 
 jobs:
   r-build:
@@ -26,51 +32,71 @@ jobs:
     steps:
       - checkout
       - run:
-          name: Install rig
-          shell: powershell.exe
+          name: Set environment
           command: |
-            choco install rig -y
+            echo "export R_LIBS=$HOME/Rlibs" >> $BASH_ENV
       - run:
-          name: Install R << parameters.r-version >> (win)
-          shell: powershell.exe
+          name: Install R << parameters.r-version >>
           command: |
-            $R_VERSION = "<< parameters.r-version >>"
-            rig add $R_VERSION
+            R_VERSION="<< parameters.r-version >>"
+            # Install rig, R Installation Manager (https://github.com/r-lib/rig) to control installed R version
+            if [ "$RUNNER_OS" == "macos" ]; then
+              brew tap r-lib/rig
+              brew install --cask rig
+              rig add $R_VERSION
+              # on macOS the R package is installed into a MAJOR.MINOR directory
+              # the PATCH is ignored (only one patch version supported) the
+              # architecture is added as a suffix (arm64, x86_64) to allow for
+              # installations to coexist
+              rig default "${R_VERSION%.*}-arm64"
+            elif [ "$RUNNER_OS" == "linux" ]; then
+              `which sudo` curl -L https://rig.r-pkg.org/deb/rig.gpg -o /etc/apt/trusted.gpg.d/rig.gpg
+              `which sudo` sh -c 'echo "deb http://rig.r-pkg.org/deb rig main" > /etc/apt/sources.list.d/rig.list'
+              `which sudo` apt update
+              `which sudo` apt install r-rig
+              sudo rig add $R_VERSION
+              sudo rig default $R_VERSION
+            fi
       - run:
-          name: Install Rtools
-          shell: powershell.exe
+          name: System Dependencies
           command: |
-            choco install rtools -y
+            if [ "$RUNNER_OS" == "linux" ]; then
+              sudo apt-get -y update
+              sudo apt-get install -y cmake libcurl4-openssl-dev libssh2-1-dev libharfbuzz-dev libfribidi-dev gh
+              sudo rm -rf /var/lib/apt/lists/*
+            elif [ "$RUNNER_OS" == "macos" ]; then
+              brew install cmake
+            fi
+      - run:
+          name: Configuration Information
+          command: |
+            mkdir -p ${R_LIBS}
+            c++ --version
+            cmake --version || echo "cmake not found"
+            which R
+            R --version
       - run:
           name: Install R packages
-          shell: powershell.exe
           command: |
-            $R_VERSION = "<< parameters.r-version >>"
-            $RBin = "C:\Program Files\R\R-$R_VERSION\bin"
-            $Env:Path = "$Env:Path;$RBin"
-            Rscript.exe -e "install.packages(c('remotes'), repos='https://cloud.r-project.org/')"
+            R -e "install.packages(c('remotes'), lib=c('${R_LIBS}'), repo='https://cloud.r-project.org/')"
       - run:
           name: Build and test
-          shell: powershell.exe
           no_output_timeout: 30m
           command: |
-            $R_VERSION = "<< parameters.r-version >>"
-            $RTOOLS_HOME = "C:\rtools45"
-            $RBin = "C:\Program Files\R\R-$R_VERSION\bin"
-            $RtoolsBin = "C:\rtools45\usr\bin;C:\rtools45\x86_64-w64-mingw32.static.posix\bin"
-            $Env:Path = "$Env:Path;$RBin;$RtoolsBin"
-            $Env:Path
-            $MAKEJ=8
-            Rscript.exe  -e "remotes::install_git('.')"
+            set -x
+            R -e "remotes::install_git(c('.'), lib=c('${R_LIBS}'), configure.vars=c('MAKEJ=3'))"
+
 workflows:
-  r-build-test:
+  r-release:
+    # Runs on: push to main, pull requests to main, manual trigger, and scheduled runs
     jobs:
-      - r-build:
+      - r-release:
           matrix:
             parameters:
-              r-version: ['4.4.1']
-              os: ["windows"]
+              r-version: ['4.5.2']
+              os: ["macos-arm"]
           filters:
             branches:
               only:
-                - release
+                - main
+                - /pull\/.*/  # Run on all pull request branches
